[package]
name = "fun_os"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[build]
build-stage = 1
target = ["x86_64-unknown-none"]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
